macro(INTEGRATE_MYSQL)
set(MYSQL_COMPONENTS ${ARGV})
MESSAGE( STATUS "Searching next MYSQL libraries:"${MYSQL_COMPONENTS} "..." )
if(NOT MYSQLCONNECTORCPP_ROOT_DIR AND NOT $ENV{MYSQLCONNECTORCPP_ROOT_DIR} STREQUAL "")
    FILE( TO_CMAKE_PATH $ENV{MYSQLCONNECTORCPP_ROOT_DIR} MYSQLCONNECTORCPP_ROOT_DIR )
    if( NOT EXISTS ${MYSQLCONNECTORCPP_ROOT_DIR} )
        MESSAGE( STATUS  ${MYSQLCONNECTORCPP_ROOT_DIR} " does not exist. Checking if MYSQLCONNECTORCPP_ROOT_DIR was a quoted string.." )
        STRING( REPLACE "\"" "" BOOST_ROOT ${MYSQLCONNECTORCPP_ROOT_DIR} )
        if( EXISTS ${MYSQLCONNECTORCPP_ROOT_DIR} )
            MESSAGE( STATUS "After removing the quotes " ${MYSQLCONNECTORCPP_ROOT_DIR} " was now found by CMake" )
        endif( EXISTS ${MYSQLCONNECTORCPP_ROOT_DIR})
    endif( NOT EXISTS ${MYSQLCONNECTORCPP_ROOT_DIR} )

# Save the MYSQLCONNECTORCPP_ROOT_DIR in the cache
    if( NOT EXISTS ${MYSQLCONNECTORCPP_ROOT_DIR} )
        MESSAGE( WARNING ${MYSQLCONNECTORCPP_ROOT_DIR} " does not exist." )
    else(NOT EXISTS ${MYSQLCONNECTORCPP_ROOT_DIR})
        SET (MYSQLCONNECTORCPP_ROOT_DIR ${MYSQLCONNECTORCPP_ROOT_DIR} CACHE PATH "Set the value of MYSQLCONNECTORCPP_ROOT_DIR to point to the root folder of your boost install." FORCE)
    endif( NOT EXISTS ${MYSQLCONNECTORCPP_ROOT_DIR} )

endif(NOT MYSQLCONNECTORCPP_ROOT_DIR AND NOT $ENV{MYSQLCONNECTORCPP_ROOT_DIR} STREQUAL "")

if(WIN32)
        find_path(MYSQLCONNECTORCPP_INCLUDE_DIR
                NAMES
                mysql_connection.h
                PATHS
                "C:\\Program Files"
                HINTS
                ${MYSQLCONNECTORCPP_ROOT_DIR}
                PATH_SUFFIXES
                include)

        find_library(MYSQLCONNECTORCPP_LIBRARY
                NAMES
                ${MYSQL_COMPONENTS}
                HINTS
                ${MYSQLCONNECTORCPP_ROOT_DIR}
                PATH_SUFFIXES
                lib)

else()
        FIND_PATH(MYSQLCONNECTORCPP_INCLUDE_DIR mysql_connection.h PATHS ${MYSQLCONNECTORCPP_ROOT_DIR} PATH_SUFFIXES include)
        FIND_LIBRARY(MYSQLCONNECTORCPP_LIBRARY ${MYSQL_COMPONENTS} PATHS ${MYSQLCONNECTORCPP_ROOT_DIR} PATH_SUFFIXES lib64 lib)
endif()

if(EXISTS ${MYSQLCONNECTORCPP_INCLUDE_DIR} AND NOT ${MYSQLCONNECTORCPP_LIBRARY} STREQUAL "")
        MESSAGE (STATUS "Found MYSQL DIR:${MYSQLCONNECTORCPP_INCLUDE_DIR}, LIB:${MYSQLCONNECTORCPP_LIBRARY}")
        set(MYSQLCONNECTORCPP_INCLUDE_DIRS "${MYSQLCONNECTORCPP_INCLUDE_DIR}") # Add any dependencies here
        set(MYSQLCONNECTORCPP_LIBRARIES "${MYSQLCONNECTORCPP_LIBRARY}") # Add any dependencies here
ELSE (EXISTS ${MYSQLCONNECTORCPP_INCLUDE_DIR} AND NOT ${MYSQLCONNECTORCPP_LIBRARY} STREQUAL "")
        MESSAGE(FATAL_ERROR "MYSQL not founded.")
endif()
endmacro(INTEGRATE_MYSQL)

macro(INSTALL_MYSQL TARGET_NAME ADDING_LIBS)

endmacro(INSTALL_MYSQL)
